### ISSUE TITLE
downsize filter ?

### ISSUE THREAD

**Issue by adriens** [keshrath/Giphy4J#3]
Hi guys,

your lib is very convenient and easy to use : it does perfectly fit my needs ...at an exception : i didn't find how to query gifs with the downsize. I could not find sample code to do that :

`SearchRandom giphyData = giphy.searchRandomS("Happy birthday");`

In my case, i make a random search and want to be sure that the gif will be displayed. Iwas the downsized param, i guess it's the good one.
Sticketrs are nice and seem to be lighter but it seems like there are more funny gifs than stickers.

Could you share some code snippet on your README.md to show how to achieve this please ?

Thank you in advance for your help.

Kind Regards,

Adrien

**Comment by adriens** [comment]
Hi, sorry for asking you, but would you have any idea on how to filter on gif size please ?

Thanks a lot for your help. :smile_cat:

**Comment by keshrath** [comment]
Hi, I don't think, you can search for downsized gifs, rather then every gif has a downsized URL.

**Comment by adriens** [comment]
Ok, thanks, i'll keep searching on getting the downsized url. Thanks for the tip.
Btw, did you implement this kind of method ?..or will you ?

**Comment by adriens** [comment]
It seems like it's not implemented on the Giohy part : https://developers.giphy.com/docs/
